from __future__ import annotations

import os
import math
import base64
import statistics
import urllib.request
import json as json_mod
from datetime import date as datetime_date
from typing import Optional, List

import yfinance as yf
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from config import RESEND_API_KEY
from models import EmailReportBody

router = APIRouter()

@router.post("/email-report")
def email_report(body: EmailReportBody):
    if not RESEND_API_KEY:
        raise HTTPException(status_code=503, detail="Email is not configured (missing RESEND_API_KEY).")

    # Strip a possible data-URL prefix and decode
    b64 = body.pdf_base64
    if "," in b64 and b64.strip().startswith("data:"):
        b64 = b64.split(",", 1)[1]
    try:
        pdf_bytes = base64.b64decode(b64)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid PDF data.")

    import resend
    resend.api_key = RESEND_API_KEY
    ticker = body.ticker.upper()
    try:
        resend.Emails.send({
            # onboarding@resend.dev works without a verified domain (test sender).
            "from": "Moat <onboarding@resend.dev>",
            "to": [body.to_email],
            "subject": f"Your Moat Report: {ticker}",
            "html": (
                f"<p>Attached is your Moat analysis report for <strong>{ticker}</strong>.</p>"
                f"<p style='color:#888;font-size:12px'>Generated by Moat — not financial advice.</p>"
            ),
            "attachments": [{
                "filename": f"Moat-{ticker}-Report.pdf",
                "content": list(pdf_bytes),
            }],
        })
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Email failed: {e}")

    return {"ok": True, "sent_to": body.to_email}


# ---------------------------------------------------------------------------
# Deep Research Report (full diligence) — Gemini primary, 24h cache
# ---------------------------------------------------------------------------

